### ISSUE TITLE
Add environment variable for location

### ISSUE THREAD

**Issue by iethem** [wallneradam/docker-tor-proxy#1]
Hello. 
How can I add location when I run the docker image? (e.g. -e LOCATION=US)

**Comment by wallneradam** [comment]
If you mean to restrict exit nodes to a country, it is not possible to configure by environment variables.
According to the Tor manual, you can filter exit nodes in the torrc file:
https://2019.www.torproject.org/docs/tor-manual.html.en

You can download the torrc from this repo modify it with the setting you want and mount it into docker container with the "-v" parameter: -v $PWD/torrc:/opt/tor/torrc
